services:
  - type: web
    name: Glitch
    env: node
    buildCommand: npm install
    startCommand: npm start
    plan: starter
    envVars:
      - key: NODE_ENV 
        value: production
    region: oregon
